#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduSpecDataService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EduSpec Data")]
	public partial class EduSpecDataServiceDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EduSpecDataServiceDataContext() : 
				base(global::EduSpecDataService.Properties.Settings.Default.EduSpec_DataConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecDataServiceDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecDataServiceDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecDataServiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecDataServiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_Account_NewInstitutions_View")]
		public ISingleResult<Get_Account_NewInstitutions_ViewResult> Get_Account_NewInstitutions_View()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_Account_NewInstitutions_ViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Integration_SASAMS_ClearImportTables")]
		public int Integration_SASAMS_ClearImportTables([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_SysParams", IsComposable=true)]
		public IQueryable<fn_Get_SysParamsResult> fn_Get_SysParams()
		{
			return this.CreateMethodCallQuery<fn_Get_SysParamsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EduspecData_SASAMS_ClearImportTables")]
		public int EduspecData_SASAMS_ClearImportTables([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class Get_Account_NewInstitutions_ViewResult
	{
		
		private int _InstID;
		
		private int _MasterInstID;
		
		private string _Name;
		
		private string _EMISNo;
		
		private byte _QuintileID;
		
		private byte _PhaseID;
		
		private string _PhysAddress1;
		
		private string _PhysAddress2;
		
		private string _PhysAddress3;
		
		private System.Nullable<byte> _PhysProvinceID;
		
		private string _PhysCode;
		
		private string _PosAddress1;
		
		private string _PosAddress2;
		
		private string _PosAddress3;
		
		private System.Nullable<byte> _PosProvinceID;
		
		private string _PosCode;
		
		private string _Telephone;
		
		private string _Cell;
		
		private string _Fax;
		
		private string _InstEmail;
		
		private System.Nullable<int> _PrincipalID;
		
		private System.Nullable<int> _FinancialSecretoryID;
		
		private System.Nullable<int> _GoverningBodyID;
		
		private System.Nullable<int> _GoverningFinanceID;
		
		private bool _IsActive;
		
		private string _FullName;
		
		private string _Surname;
		
		private string _Email;
		
		private bool _IsRequestEvaluation;
		
		private string _Password;
		
		private int _CorrespondenceLanguageID;
		
		private int _GradeFromID;
		
		private int _GradeToID;
		
		private System.Nullable<int> _IntegrationTypeID;
		
		public Get_Account_NewInstitutions_ViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int NOT NULL")]
		public int InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterInstID", DbType="Int NOT NULL")]
		public int MasterInstID
		{
			get
			{
				return this._MasterInstID;
			}
			set
			{
				if ((this._MasterInstID != value))
				{
					this._MasterInstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMISNo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string EMISNo
		{
			get
			{
				return this._EMISNo;
			}
			set
			{
				if ((this._EMISNo != value))
				{
					this._EMISNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuintileID", DbType="TinyInt NOT NULL")]
		public byte QuintileID
		{
			get
			{
				return this._QuintileID;
			}
			set
			{
				if ((this._QuintileID != value))
				{
					this._QuintileID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhaseID", DbType="TinyInt NOT NULL")]
		public byte PhaseID
		{
			get
			{
				return this._PhaseID;
			}
			set
			{
				if ((this._PhaseID != value))
				{
					this._PhaseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysAddress1", DbType="VarChar(50)")]
		public string PhysAddress1
		{
			get
			{
				return this._PhysAddress1;
			}
			set
			{
				if ((this._PhysAddress1 != value))
				{
					this._PhysAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysAddress2", DbType="VarChar(50)")]
		public string PhysAddress2
		{
			get
			{
				return this._PhysAddress2;
			}
			set
			{
				if ((this._PhysAddress2 != value))
				{
					this._PhysAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysAddress3", DbType="VarChar(50)")]
		public string PhysAddress3
		{
			get
			{
				return this._PhysAddress3;
			}
			set
			{
				if ((this._PhysAddress3 != value))
				{
					this._PhysAddress3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysProvinceID", DbType="TinyInt")]
		public System.Nullable<byte> PhysProvinceID
		{
			get
			{
				return this._PhysProvinceID;
			}
			set
			{
				if ((this._PhysProvinceID != value))
				{
					this._PhysProvinceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysCode", DbType="VarChar(7)")]
		public string PhysCode
		{
			get
			{
				return this._PhysCode;
			}
			set
			{
				if ((this._PhysCode != value))
				{
					this._PhysCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosAddress1", DbType="VarChar(50)")]
		public string PosAddress1
		{
			get
			{
				return this._PosAddress1;
			}
			set
			{
				if ((this._PosAddress1 != value))
				{
					this._PosAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosAddress2", DbType="VarChar(50)")]
		public string PosAddress2
		{
			get
			{
				return this._PosAddress2;
			}
			set
			{
				if ((this._PosAddress2 != value))
				{
					this._PosAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosAddress3", DbType="VarChar(50)")]
		public string PosAddress3
		{
			get
			{
				return this._PosAddress3;
			}
			set
			{
				if ((this._PosAddress3 != value))
				{
					this._PosAddress3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosProvinceID", DbType="TinyInt")]
		public System.Nullable<byte> PosProvinceID
		{
			get
			{
				return this._PosProvinceID;
			}
			set
			{
				if ((this._PosProvinceID != value))
				{
					this._PosProvinceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosCode", DbType="VarChar(7)")]
		public string PosCode
		{
			get
			{
				return this._PosCode;
			}
			set
			{
				if ((this._PosCode != value))
				{
					this._PosCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(30)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cell", DbType="VarChar(30)")]
		public string Cell
		{
			get
			{
				return this._Cell;
			}
			set
			{
				if ((this._Cell != value))
				{
					this._Cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(30)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstEmail", DbType="VarChar(100)")]
		public string InstEmail
		{
			get
			{
				return this._InstEmail;
			}
			set
			{
				if ((this._InstEmail != value))
				{
					this._InstEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrincipalID", DbType="Int")]
		public System.Nullable<int> PrincipalID
		{
			get
			{
				return this._PrincipalID;
			}
			set
			{
				if ((this._PrincipalID != value))
				{
					this._PrincipalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinancialSecretoryID", DbType="Int")]
		public System.Nullable<int> FinancialSecretoryID
		{
			get
			{
				return this._FinancialSecretoryID;
			}
			set
			{
				if ((this._FinancialSecretoryID != value))
				{
					this._FinancialSecretoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoverningBodyID", DbType="Int")]
		public System.Nullable<int> GoverningBodyID
		{
			get
			{
				return this._GoverningBodyID;
			}
			set
			{
				if ((this._GoverningBodyID != value))
				{
					this._GoverningBodyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoverningFinanceID", DbType="Int")]
		public System.Nullable<int> GoverningFinanceID
		{
			get
			{
				return this._GoverningFinanceID;
			}
			set
			{
				if ((this._GoverningFinanceID != value))
				{
					this._GoverningFinanceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(100)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(100)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequestEvaluation", DbType="Bit NOT NULL")]
		public bool IsRequestEvaluation
		{
			get
			{
				return this._IsRequestEvaluation;
			}
			set
			{
				if ((this._IsRequestEvaluation != value))
				{
					this._IsRequestEvaluation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrespondenceLanguageID", DbType="Int NOT NULL")]
		public int CorrespondenceLanguageID
		{
			get
			{
				return this._CorrespondenceLanguageID;
			}
			set
			{
				if ((this._CorrespondenceLanguageID != value))
				{
					this._CorrespondenceLanguageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeFromID", DbType="Int NOT NULL")]
		public int GradeFromID
		{
			get
			{
				return this._GradeFromID;
			}
			set
			{
				if ((this._GradeFromID != value))
				{
					this._GradeFromID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeToID", DbType="Int NOT NULL")]
		public int GradeToID
		{
			get
			{
				return this._GradeToID;
			}
			set
			{
				if ((this._GradeToID != value))
				{
					this._GradeToID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntegrationTypeID", DbType="Int")]
		public System.Nullable<int> IntegrationTypeID
		{
			get
			{
				return this._IntegrationTypeID;
			}
			set
			{
				if ((this._IntegrationTypeID != value))
				{
					this._IntegrationTypeID = value;
				}
			}
		}
	}
	
	public partial class fn_Get_SysParamsResult
	{
		
		private System.Nullable<decimal> _VAT;
		
		private string _VATNumber;
		
		private System.Nullable<int> _InstID;
		
		private string _AccessDatabaseFilePath;
		
		private string _AccessDatabaseProvider;
		
		private string _SASAMS_Password;
		
		private string _SQL_Server;
		
		private string _SQL_Database;
		
		private string _SQL_User;
		
		private string _SQL_Password;
		
		public fn_Get_SysParamsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="Decimal(6,3)")]
		public System.Nullable<decimal> VAT
		{
			get
			{
				return this._VAT;
			}
			set
			{
				if ((this._VAT != value))
				{
					this._VAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATNumber", DbType="VarChar(20)")]
		public string VATNumber
		{
			get
			{
				return this._VATNumber;
			}
			set
			{
				if ((this._VATNumber != value))
				{
					this._VATNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessDatabaseFilePath", DbType="VarChar(250)")]
		public string AccessDatabaseFilePath
		{
			get
			{
				return this._AccessDatabaseFilePath;
			}
			set
			{
				if ((this._AccessDatabaseFilePath != value))
				{
					this._AccessDatabaseFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessDatabaseProvider", DbType="VarChar(150)")]
		public string AccessDatabaseProvider
		{
			get
			{
				return this._AccessDatabaseProvider;
			}
			set
			{
				if ((this._AccessDatabaseProvider != value))
				{
					this._AccessDatabaseProvider = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SASAMS_Password", DbType="VarChar(10)")]
		public string SASAMS_Password
		{
			get
			{
				return this._SASAMS_Password;
			}
			set
			{
				if ((this._SASAMS_Password != value))
				{
					this._SASAMS_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL_Server", DbType="VarChar(150)")]
		public string SQL_Server
		{
			get
			{
				return this._SQL_Server;
			}
			set
			{
				if ((this._SQL_Server != value))
				{
					this._SQL_Server = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL_Database", DbType="VarChar(50)")]
		public string SQL_Database
		{
			get
			{
				return this._SQL_Database;
			}
			set
			{
				if ((this._SQL_Database != value))
				{
					this._SQL_Database = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL_User", DbType="VarChar(50)")]
		public string SQL_User
		{
			get
			{
				return this._SQL_User;
			}
			set
			{
				if ((this._SQL_User != value))
				{
					this._SQL_User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL_Password", DbType="VarChar(50)")]
		public string SQL_Password
		{
			get
			{
				return this._SQL_Password;
			}
			set
			{
				if ((this._SQL_Password != value))
				{
					this._SQL_Password = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
