#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduSpecWebAPI.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EduSpec WebAPI DEV")]
	public partial class EduSpecWebAPIDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EduSpecWebAPIDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecWebAPIDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecWebAPIDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecWebAPIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecWebAPIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_WebAPI_Learners")]
		public ISingleResult<Get_WebAPI_LearnersResult> Get_WebAPI_Learners([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((ISingleResult<Get_WebAPI_LearnersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_WebAPI_Family")]
		public ISingleResult<Get_WebAPI_FamilyResult> Get_WebAPI_Family([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FamilyID", DbType="Int")] System.Nullable<int> familyID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), familyID);
			return ((ISingleResult<Get_WebAPI_FamilyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_WebAPI_Families")]
		public ISingleResult<Get_WebAPI_FamiliesResult> Get_WebAPI_Families([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((ISingleResult<Get_WebAPI_FamiliesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_WebAPI_Learners")]
		public int Set_WebAPI_Learners(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LearnerID", DbType="VarChar(50)")] string learnerID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AccessionNo", DbType="VarChar(50)")] string accessionNo, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EntryDate", DbType="VarChar(20)")] string entryDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateLeft", DbType="VarChar(50)")] string dateLeft, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(10)")] string title, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Initials", DbType="VarChar(10)")] string initials, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullName", DbType="VarChar(255)")] string fullName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Surname", DbType="VarChar(100)")] string surname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="BirthDate", DbType="VarChar(50)")] string birthDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNumber", DbType="VarChar(20)")] string iDNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(20)")] string gender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Language", DbType="VarChar(20)")] string language, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelHome", DbType="VarChar(255)")] string telHome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelCell", DbType="VarChar(255)")] string telCell, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(250)")] string email, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GradeID", DbType="Int")] System.Nullable<int> gradeID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClassID", DbType="Int")] System.Nullable<int> classID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ClassName", DbType="VarChar(50)")] string className, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Race", DbType="VarChar(50)")] string race, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="LuritsNumber", DbType="Float")] System.Nullable<double> luritsNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(20)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, iD, learnerID, accessionNo, entryDate, dateLeft, title, initials, fullName, surname, birthDate, iDNumber, gender, language, telHome, telCell, email, gradeID, classID, className, race, luritsNumber, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_WebAPI_LearnersClear")]
		public int Set_WebAPI_LearnersClear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_WebAPI_ParentChild")]
		public ISingleResult<Get_WebAPI_ParentChildResult> Get_WebAPI_ParentChild([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((ISingleResult<Get_WebAPI_ParentChildResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_WebAPI_ParentChild")]
		public int Set_WebAPI_ParentChild([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChildID", DbType="Int")] System.Nullable<int> childID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LearnerID", DbType="VarChar(50)")] string learnerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(20)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FamilyCode", DbType="VarChar(200)")] string familyCode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, parentID, childID, learnerID, status, familyCode);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_WebAPI_ParentChildClear")]
		public int Set_WebAPI_ParentChildClear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_WebAPI_Parents")]
		public ISingleResult<Get_WebAPI_ParentsResult> Get_WebAPI_Parents([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((ISingleResult<Get_WebAPI_ParentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_WebAPI_Parents")]
		public int Set_WebAPI_Parents(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Title", DbType="VarChar(20)")] string title, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Initials", DbType="VarChar(10)")] string initials, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullName", DbType="VarChar(100)")] string fullName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Surname", DbType="VarChar(100)")] string surname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDNumber", DbType="VarChar(20)")] string iDNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Employer", DbType="VarChar(100)")] string employer, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Occupation", DbType="VarChar(60)")] string occupation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StreetAddress1", DbType="VarChar(70)")] string streetAddress1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StreetAddress2", DbType="VarChar(70)")] string streetAddress2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StreetAddress3", DbType="VarChar(50)")] string streetAddress3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StreetCode", DbType="VarChar(10)")] string streetCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostalAddress1", DbType="VarChar(70)")] string postalAddress1, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostalAddress2", DbType="VarChar(70)")] string postalAddress2, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostalAddress3", DbType="VarChar(50)")] string postalAddress3, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PostalCode", DbType="VarChar(10)")] string postalCode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelHome", DbType="VarChar(50)")] string telHome, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelWork", DbType="VarChar(50)")] string telWork, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelCell", DbType="VarChar(50)")] string telCell, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="TelFax", DbType="VarChar(50)")] string telFax, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="EMail", DbType="VarChar(250)")] string eMail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="VarChar(20)")] string gender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Homelanguage", DbType="VarChar(50)")] string homelanguage, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseFullName", DbType="VarChar(100)")] string spouseFullName, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseSurname", DbType="VarChar(50)")] string spouseSurname, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseIDNumber", DbType="VarChar(200)")] string spouseIDNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseOccupation", DbType="VarChar(100)")] string spouseOccupation, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseWorkTel", DbType="VarChar(30)")] string spouseWorkTel, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseGender", DbType="VarChar(50)")] string spouseGender, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseCell", DbType="VarChar(200)")] string spouseCell, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="SpouseEmail", DbType="VarChar(250)")] string spouseEmail, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaritalStatus", DbType="VarChar(200)")] string maritalStatus, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Relationship", DbType="VarChar(50)")] string relationship, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="VarChar(10)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, parentID, title, initials, fullName, surname, iDNumber, employer, occupation, streetAddress1, streetAddress2, streetAddress3, streetCode, postalAddress1, postalAddress2, postalAddress3, postalCode, telHome, telWork, telCell, telFax, eMail, gender, homelanguage, spouseFullName, spouseSurname, spouseIDNumber, spouseOccupation, spouseWorkTel, spouseGender, spouseCell, spouseEmail, maritalStatus, relationship, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_WebAPI_ParentsClear")]
		public int Set_WebAPI_ParentsClear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_WebAPI_Transactions")]
		public int Set_WebAPI_Transactions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LearnerID", DbType="Int")] System.Nullable<int> learnerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DateDone", DbType="DateTime")] System.Nullable<System.DateTime> dateDone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(100)")] string description, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Amount", DbType="Money")] System.Nullable<decimal> amount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, learnerID, dateDone, description, amount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_WebAPI_TransactionsClear")]
		public int Set_WebAPI_TransactionsClear([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_WebAPI_SysParams")]
		public ISingleResult<Get_WebAPI_SysParamsResult> Get_WebAPI_SysParams([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((ISingleResult<Get_WebAPI_SysParamsResult>)(result.ReturnValue));
		}
	}
	
	public partial class Get_WebAPI_LearnersResult
	{
		
		private int _InstID;
		
		private int _ID;
		
		private string _LearnerID;
		
		private string _AccessionNo;
		
		private string _EntryDate;
		
		private string _DateLeft;
		
		private string _Title;
		
		private string _Initials;
		
		private string _FullName;
		
		private string _Surname;
		
		private string _BirthDate;
		
		private string _IDNumber;
		
		private string _Gender;
		
		private string _Language;
		
		private string _TelHome;
		
		private string _TelCell;
		
		private string _Email;
		
		private int _GradeID;
		
		private int _ClassID;
		
		private string _ClassName;
		
		private string _Race;
		
		private System.Nullable<double> _LuritsNumber;
		
		private string _Status;
		
		public Get_WebAPI_LearnersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int NOT NULL")]
		public int InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LearnerID", DbType="VarChar(50)")]
		public string LearnerID
		{
			get
			{
				return this._LearnerID;
			}
			set
			{
				if ((this._LearnerID != value))
				{
					this._LearnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessionNo", DbType="VarChar(50)")]
		public string AccessionNo
		{
			get
			{
				return this._AccessionNo;
			}
			set
			{
				if ((this._AccessionNo != value))
				{
					this._AccessionNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryDate", DbType="VarChar(20)")]
		public string EntryDate
		{
			get
			{
				return this._EntryDate;
			}
			set
			{
				if ((this._EntryDate != value))
				{
					this._EntryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateLeft", DbType="VarChar(50)")]
		public string DateLeft
		{
			get
			{
				return this._DateLeft;
			}
			set
			{
				if ((this._DateLeft != value))
				{
					this._DateLeft = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(10)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Initials", DbType="VarChar(10)")]
		public string Initials
		{
			get
			{
				return this._Initials;
			}
			set
			{
				if ((this._Initials != value))
				{
					this._Initials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(255)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(100)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthDate", DbType="VarChar(50)")]
		public string BirthDate
		{
			get
			{
				return this._BirthDate;
			}
			set
			{
				if ((this._BirthDate != value))
				{
					this._BirthDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNumber", DbType="VarChar(20)")]
		public string IDNumber
		{
			get
			{
				return this._IDNumber;
			}
			set
			{
				if ((this._IDNumber != value))
				{
					this._IDNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(20)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="VarChar(20)")]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this._Language = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="VarChar(255)")]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this._TelHome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelCell", DbType="VarChar(255)")]
		public string TelCell
		{
			get
			{
				return this._TelCell;
			}
			set
			{
				if ((this._TelCell != value))
				{
					this._TelCell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(250)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeID", DbType="Int NOT NULL")]
		public int GradeID
		{
			get
			{
				return this._GradeID;
			}
			set
			{
				if ((this._GradeID != value))
				{
					this._GradeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassID", DbType="Int NOT NULL")]
		public int ClassID
		{
			get
			{
				return this._ClassID;
			}
			set
			{
				if ((this._ClassID != value))
				{
					this._ClassID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassName", DbType="VarChar(50)")]
		public string ClassName
		{
			get
			{
				return this._ClassName;
			}
			set
			{
				if ((this._ClassName != value))
				{
					this._ClassName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Race", DbType="VarChar(50)")]
		public string Race
		{
			get
			{
				return this._Race;
			}
			set
			{
				if ((this._Race != value))
				{
					this._Race = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuritsNumber", DbType="Float")]
		public System.Nullable<double> LuritsNumber
		{
			get
			{
				return this._LuritsNumber;
			}
			set
			{
				if ((this._LuritsNumber != value))
				{
					this._LuritsNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class Get_WebAPI_FamilyResult
	{
		
		private int _FamilyID;
		
		private string _FamilyCode;
		
		private string _AccountNumber;
		
		public Get_WebAPI_FamilyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyID", DbType="Int NOT NULL")]
		public int FamilyID
		{
			get
			{
				return this._FamilyID;
			}
			set
			{
				if ((this._FamilyID != value))
				{
					this._FamilyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FamilyCode
		{
			get
			{
				return this._FamilyCode;
			}
			set
			{
				if ((this._FamilyCode != value))
				{
					this._FamilyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="VarChar(15)")]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this._AccountNumber = value;
				}
			}
		}
	}
	
	public partial class Get_WebAPI_FamiliesResult
	{
		
		private int _FamilyID;
		
		private string _FamilyCode;
		
		private string _AccountNumber;
		
		public Get_WebAPI_FamiliesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyID", DbType="Int NOT NULL")]
		public int FamilyID
		{
			get
			{
				return this._FamilyID;
			}
			set
			{
				if ((this._FamilyID != value))
				{
					this._FamilyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string FamilyCode
		{
			get
			{
				return this._FamilyCode;
			}
			set
			{
				if ((this._FamilyCode != value))
				{
					this._FamilyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNumber", DbType="VarChar(15)")]
		public string AccountNumber
		{
			get
			{
				return this._AccountNumber;
			}
			set
			{
				if ((this._AccountNumber != value))
				{
					this._AccountNumber = value;
				}
			}
		}
	}
	
	public partial class Get_WebAPI_ParentChildResult
	{
		
		private int _InstID;
		
		private int _ParentId;
		
		private int _ChildId;
		
		private string _Learnerid;
		
		private string _Status;
		
		private string _FamilyCode;
		
		public Get_WebAPI_ParentChildResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int NOT NULL")]
		public int InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentId", DbType="Int NOT NULL")]
		public int ParentId
		{
			get
			{
				return this._ParentId;
			}
			set
			{
				if ((this._ParentId != value))
				{
					this._ParentId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChildId", DbType="Int NOT NULL")]
		public int ChildId
		{
			get
			{
				return this._ChildId;
			}
			set
			{
				if ((this._ChildId != value))
				{
					this._ChildId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Learnerid", DbType="VarChar(50)")]
		public string Learnerid
		{
			get
			{
				return this._Learnerid;
			}
			set
			{
				if ((this._Learnerid != value))
				{
					this._Learnerid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(20)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyCode", DbType="VarChar(200)")]
		public string FamilyCode
		{
			get
			{
				return this._FamilyCode;
			}
			set
			{
				if ((this._FamilyCode != value))
				{
					this._FamilyCode = value;
				}
			}
		}
	}
	
	public partial class Get_WebAPI_ParentsResult
	{
		
		private int _InstID;
		
		private int _ParentID;
		
		private string _Title;
		
		private string _Initials;
		
		private string _FullName;
		
		private string _Surname;
		
		private string _IDNumber;
		
		private string _Employer;
		
		private string _Occupation;
		
		private string _StreetAddress1;
		
		private string _StreetAddress2;
		
		private string _StreetAddress3;
		
		private string _StreetCode;
		
		private string _PostalAddress1;
		
		private string _PostalAddress2;
		
		private string _PostalAddress3;
		
		private string _PostalCode;
		
		private string _TelHome;
		
		private string _TelWork;
		
		private string _TelCell;
		
		private string _TelFax;
		
		private string _EMail;
		
		private string _Gender;
		
		private string _Homelanguage;
		
		private string _SpouseFullName;
		
		private string _SpouseSurname;
		
		private string _SpouseIDNumber;
		
		private string _SpouseOccupation;
		
		private string _SpouseWorkTel;
		
		private string _SpouseGender;
		
		private string _SpouseCell;
		
		private string _SpouseEmail;
		
		private string _MaritalStatus;
		
		private string _Relationship;
		
		private string _Status;
		
		public Get_WebAPI_ParentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int NOT NULL")]
		public int InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="VarChar(20)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Initials", DbType="VarChar(10)")]
		public string Initials
		{
			get
			{
				return this._Initials;
			}
			set
			{
				if ((this._Initials != value))
				{
					this._Initials = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(100)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(100)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDNumber", DbType="VarChar(20)")]
		public string IDNumber
		{
			get
			{
				return this._IDNumber;
			}
			set
			{
				if ((this._IDNumber != value))
				{
					this._IDNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employer", DbType="VarChar(100)")]
		public string Employer
		{
			get
			{
				return this._Employer;
			}
			set
			{
				if ((this._Employer != value))
				{
					this._Employer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="VarChar(60)")]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this._Occupation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress1", DbType="VarChar(70)")]
		public string StreetAddress1
		{
			get
			{
				return this._StreetAddress1;
			}
			set
			{
				if ((this._StreetAddress1 != value))
				{
					this._StreetAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress2", DbType="VarChar(70)")]
		public string StreetAddress2
		{
			get
			{
				return this._StreetAddress2;
			}
			set
			{
				if ((this._StreetAddress2 != value))
				{
					this._StreetAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress3", DbType="VarChar(50)")]
		public string StreetAddress3
		{
			get
			{
				return this._StreetAddress3;
			}
			set
			{
				if ((this._StreetAddress3 != value))
				{
					this._StreetAddress3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetCode", DbType="VarChar(10)")]
		public string StreetCode
		{
			get
			{
				return this._StreetCode;
			}
			set
			{
				if ((this._StreetCode != value))
				{
					this._StreetCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalAddress1", DbType="VarChar(70)")]
		public string PostalAddress1
		{
			get
			{
				return this._PostalAddress1;
			}
			set
			{
				if ((this._PostalAddress1 != value))
				{
					this._PostalAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalAddress2", DbType="VarChar(70)")]
		public string PostalAddress2
		{
			get
			{
				return this._PostalAddress2;
			}
			set
			{
				if ((this._PostalAddress2 != value))
				{
					this._PostalAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalAddress3", DbType="VarChar(50)")]
		public string PostalAddress3
		{
			get
			{
				return this._PostalAddress3;
			}
			set
			{
				if ((this._PostalAddress3 != value))
				{
					this._PostalAddress3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalCode", DbType="VarChar(10)")]
		public string PostalCode
		{
			get
			{
				return this._PostalCode;
			}
			set
			{
				if ((this._PostalCode != value))
				{
					this._PostalCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelHome", DbType="VarChar(50)")]
		public string TelHome
		{
			get
			{
				return this._TelHome;
			}
			set
			{
				if ((this._TelHome != value))
				{
					this._TelHome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelWork", DbType="VarChar(50)")]
		public string TelWork
		{
			get
			{
				return this._TelWork;
			}
			set
			{
				if ((this._TelWork != value))
				{
					this._TelWork = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelCell", DbType="VarChar(50)")]
		public string TelCell
		{
			get
			{
				return this._TelCell;
			}
			set
			{
				if ((this._TelCell != value))
				{
					this._TelCell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TelFax", DbType="VarChar(50)")]
		public string TelFax
		{
			get
			{
				return this._TelFax;
			}
			set
			{
				if ((this._TelFax != value))
				{
					this._TelFax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="VarChar(250)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(20)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Homelanguage", DbType="VarChar(50)")]
		public string Homelanguage
		{
			get
			{
				return this._Homelanguage;
			}
			set
			{
				if ((this._Homelanguage != value))
				{
					this._Homelanguage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseFullName", DbType="VarChar(100)")]
		public string SpouseFullName
		{
			get
			{
				return this._SpouseFullName;
			}
			set
			{
				if ((this._SpouseFullName != value))
				{
					this._SpouseFullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseSurname", DbType="VarChar(50)")]
		public string SpouseSurname
		{
			get
			{
				return this._SpouseSurname;
			}
			set
			{
				if ((this._SpouseSurname != value))
				{
					this._SpouseSurname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseIDNumber", DbType="VarChar(200)")]
		public string SpouseIDNumber
		{
			get
			{
				return this._SpouseIDNumber;
			}
			set
			{
				if ((this._SpouseIDNumber != value))
				{
					this._SpouseIDNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseOccupation", DbType="VarChar(100)")]
		public string SpouseOccupation
		{
			get
			{
				return this._SpouseOccupation;
			}
			set
			{
				if ((this._SpouseOccupation != value))
				{
					this._SpouseOccupation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseWorkTel", DbType="VarChar(30)")]
		public string SpouseWorkTel
		{
			get
			{
				return this._SpouseWorkTel;
			}
			set
			{
				if ((this._SpouseWorkTel != value))
				{
					this._SpouseWorkTel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseGender", DbType="VarChar(50)")]
		public string SpouseGender
		{
			get
			{
				return this._SpouseGender;
			}
			set
			{
				if ((this._SpouseGender != value))
				{
					this._SpouseGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseCell", DbType="VarChar(200)")]
		public string SpouseCell
		{
			get
			{
				return this._SpouseCell;
			}
			set
			{
				if ((this._SpouseCell != value))
				{
					this._SpouseCell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpouseEmail", DbType="VarChar(250)")]
		public string SpouseEmail
		{
			get
			{
				return this._SpouseEmail;
			}
			set
			{
				if ((this._SpouseEmail != value))
				{
					this._SpouseEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="VarChar(200)")]
		public string MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this._MaritalStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Relationship", DbType="VarChar(50)")]
		public string Relationship
		{
			get
			{
				return this._Relationship;
			}
			set
			{
				if ((this._Relationship != value))
				{
					this._Relationship = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(10)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
	}
	
	public partial class Get_WebAPI_SysParamsResult
	{
		
		private int _InstID;
		
		private string _SASAMS_FilePath;
		
		private string _SASAMS_Password;
		
		private string _AccessDatabaseProvider;
		
		private bool _IsSASAMSFinance;
		
		public Get_WebAPI_SysParamsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int NOT NULL")]
		public int InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SASAMS_FilePath", DbType="VarChar(150)")]
		public string SASAMS_FilePath
		{
			get
			{
				return this._SASAMS_FilePath;
			}
			set
			{
				if ((this._SASAMS_FilePath != value))
				{
					this._SASAMS_FilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SASAMS_Password", DbType="VarChar(15)")]
		public string SASAMS_Password
		{
			get
			{
				return this._SASAMS_Password;
			}
			set
			{
				if ((this._SASAMS_Password != value))
				{
					this._SASAMS_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessDatabaseProvider", DbType="VarChar(50)")]
		public string AccessDatabaseProvider
		{
			get
			{
				return this._AccessDatabaseProvider;
			}
			set
			{
				if ((this._AccessDatabaseProvider != value))
				{
					this._AccessDatabaseProvider = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSASAMSFinance", DbType="Bit NOT NULL")]
		public bool IsSASAMSFinance
		{
			get
			{
				return this._IsSASAMSFinance;
			}
			set
			{
				if ((this._IsSASAMSFinance != value))
				{
					this._IsSASAMSFinance = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
