#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduspecService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EduSpec DEV")]
	public partial class EduSpecDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public EduSpecDataDataContext() : 
				base(global::EduspecService.Properties.Settings.Default.EduSpec_DEVConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EduSpecDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_ActiveYearID", IsComposable=true)]
		public System.Nullable<int> fn_Get_ActiveYearID()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_BulkLetterInstitutionList", IsComposable=true)]
		public IQueryable<fn_Get_BulkLetterInstitutionListResult> fn_Get_BulkLetterInstitutionList()
		{
			return this.CreateMethodCallQuery<fn_Get_BulkLetterInstitutionListResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_SMSToSendCount", IsComposable=true)]
		public System.Nullable<int> fn_Get_SMSToSendCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_GenericLetter")]
		public ISingleResult<RPT_GenericLetterResult> RPT_GenericLetter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExemptionID", DbType="Int")] System.Nullable<int> exemptionID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgeFamilyID", DbType="Int")] System.Nullable<int> ageFamilyID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, exemptionID, ageFamilyID);
			return ((ISingleResult<RPT_GenericLetterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_Letterhead")]
		public ISingleResult<RPT_LetterheadResult> RPT_Letterhead([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsPrintLetterHead", DbType="Bit")] System.Nullable<bool> isPrintLetterHead)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, isPrintLetterHead);
			return ((ISingleResult<RPT_LetterheadResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_BulkSMSQueueError_Update")]
		public int Set_BulkSMSQueueError_Update([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrespondenceID", DbType="Int")] System.Nullable<int> correspondenceID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingKey", DbType="Int")] System.Nullable<int> trackingKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FailCount", DbType="Int")] System.Nullable<int> failCount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correspondenceID, trackingKey, failCount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduSpecService_BulkLettersPrinted")]
		public int Set_EduSpecService_BulkLettersPrinted([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BulkLetterTrackingKey", DbType="Int")] System.Nullable<int> bulkLetterTrackingKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bulkLetterTrackingKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduSpecService_LetterSaved")]
		public int Set_EduSpecService_LetterSaved([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrespondenceID", DbType="Int")] System.Nullable<int> correspondenceID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BulkLetterTrackingKey", DbType="Int")] System.Nullable<int> bulkLetterTrackingKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSaved", DbType="Bit")] System.Nullable<bool> isSaved, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="VarChar(250)")] string fileName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correspondenceID, bulkLetterTrackingKey, isSaved, fileName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_SMSToPrepareCount", IsComposable=true)]
		public System.Nullable<int> fn_Get_SMSToPrepareCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduSpecService_SMSSent")]
		public ISingleResult<Set_EduSpecService_SMSSentResult> Set_EduSpecService_SMSSent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrespondenceID", DbType="Int")] System.Nullable<int> correspondenceID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingKey", DbType="Int")] System.Nullable<int> trackingKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSent", DbType="Bit")] System.Nullable<bool> isSent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SMS_OUTPUT", DbType="VarChar(150)")] string sMS_OUTPUT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correspondenceID, trackingKey, isSent, sMS_OUTPUT);
			return ((ISingleResult<Set_EduSpecService_SMSSentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduSpecService_SMSReplies")]
		public int Set_EduSpecService_SMSReplies([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SMS_OUTPUT", DbType="VarChar(MAX)")] string sMS_OUTPUT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sMS_OUTPUT);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_Bulk_Letters")]
		public ISingleResult<RPT_Bulk_LettersResult> RPT_Bulk_Letters([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingKey", DbType="Int")] System.Nullable<int> trackingKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), trackingKey);
			return ((ISingleResult<RPT_Bulk_LettersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_Age_Letters")]
		public ISingleResult<RPT_Age_LettersResult> RPT_Age_Letters([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="YearID", DbType="Int")] System.Nullable<int> yearID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgeStatusID", DbType="Int")] System.Nullable<int> ageStatusID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FamilyID", DbType="Int")] System.Nullable<int> familyID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsBulkLetter", DbType="Bit")] System.Nullable<bool> isBulkLetter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LetterID", DbType="Int")] System.Nullable<int> letterID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrespondenceID", DbType="Int")] System.Nullable<int> correspondenceID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, yearID, ageStatusID, familyID, isBulkLetter, letterID, correspondenceID);
			return ((ISingleResult<RPT_Age_LettersResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_EmailToPrepareCount", IsComposable=true)]
		public System.Nullable<int> fn_Get_EmailToPrepareCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_DebtManagement_ActionHistory")]
		public ISingleResult<Set_DebtManagement_ActionHistoryResult> Set_DebtManagement_ActionHistory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FamilyID", DbType="Int")] System.Nullable<int> familyID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgeStatusID", DbType="Int")] System.Nullable<int> ageStatusID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LegalActionActionsID", DbType="Int")] System.Nullable<int> legalActionActionsID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageBody", DbType="VarChar(918)")] string messageBody, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SMSNumbers", DbType="VarChar(250)")] string sMSNumbers, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSMS", DbType="Bit")] System.Nullable<bool> isSMS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="VarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactName", DbType="VarChar(50)")] string contactName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactSurname", DbType="VarChar(50)")] string contactSurname, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LetterID", DbType="Int")] System.Nullable<int> letterID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Description", DbType="VarChar(100)")] string description)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, familyID, ageStatusID, legalActionActionsID, userID, messageBody, sMSNumbers, isSMS, email, contactName, contactSurname, letterID, description);
			return ((ISingleResult<Set_DebtManagement_ActionHistoryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_Account_NewInstitutions_View")]
		public ISingleResult<Get_Account_NewInstitutions_ViewResult> Get_Account_NewInstitutions_View()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_Account_NewInstitutions_ViewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduspecService_BulkLetterQueue_List")]
		public ISingleResult<Get_EduspecService_BulkLetterQueue_ListResult> Get_EduspecService_BulkLetterQueue_List()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduspecService_BulkLetterQueue_ListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduspecService_BulkLetterTracking_List")]
		public ISingleResult<Get_EduspecService_BulkLetterTracking_ListResult> Get_EduspecService_BulkLetterTracking_List()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduspecService_BulkLetterTracking_ListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_CorrespondenceMethod_PickList")]
		public ISingleResult<Get_CorrespondenceMethod_PickListResult> Get_CorrespondenceMethod_PickList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_CorrespondenceMethod_PickListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduSpecService_SMSsToPrepare")]
		public ISingleResult<Get_EduSpecService_SMSsToPrepareResult> Get_EduSpecService_SMSsToPrepare()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduSpecService_SMSsToPrepareResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduSpecService_SMSsToSent")]
		public ISingleResult<Get_EduSpecService_SMSsToSentResult> Get_EduSpecService_SMSsToSent()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduSpecService_SMSsToSentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduSpecService_BulkSMSCreditsUsed")]
		public int Set_EduSpecService_BulkSMSCreditsUsed([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BulkSMSTrackingKey", DbType="Int")] System.Nullable<int> bulkSMSTrackingKey)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), bulkSMSTrackingKey);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduSpecService_PrepareSMSQueue")]
		public int Set_EduSpecService_PrepareSMSQueue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingKey", DbType="Int")] System.Nullable<int> trackingKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), trackingKey, instID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduspecService_DocumentsToGenerate")]
		public ISingleResult<Get_EduspecService_DocumentsToGenerateResult> Get_EduspecService_DocumentsToGenerate()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduspecService_DocumentsToGenerateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_Statement")]
		public ISingleResult<RPT_StatementResult> RPT_Statement([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((ISingleResult<RPT_StatementResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_StatementFooter")]
		public ISingleResult<RPT_StatementFooterResult> RPT_StatementFooter([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((ISingleResult<RPT_StatementFooterResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_StatementHeader")]
		public ISingleResult<RPT_StatementHeaderResult> RPT_StatementHeader([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID);
			return ((ISingleResult<RPT_StatementHeaderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_InvoiceHeader")]
		public ISingleResult<RPT_InvoiceHeaderResult> RPT_InvoiceHeader([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceID", DbType="Int")] System.Nullable<int> invoiceID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), instID, invoiceID);
			return ((ISingleResult<RPT_InvoiceHeaderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduspecService_DocumentGenerated")]
		public int Set_EduspecService_DocumentGenerated([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrespondenceID", DbType="Int")] System.Nullable<int> correspondenceID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="VarChar(250)")] string fileName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DocumentDesc", DbType="VarChar(100)")] string documentDesc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correspondenceID, fileName, documentDesc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetEmailsToSentCount", IsComposable=true)]
		public System.Nullable<int> fn_GetEmailsToSentCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduspecService_DocumentSent")]
		public int Set_EduspecService_DocumentSent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrespondenceID", DbType="Int")] System.Nullable<int> correspondenceID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSent", DbType="Bit")] System.Nullable<bool> isSent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Error", DbType="VarChar(255)")] string error)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correspondenceID, isSent, error);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduspecService_InstitutionsToMail")]
		public ISingleResult<Get_EduspecService_InstitutionsToMailResult> Get_EduspecService_InstitutionsToMail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduspecService_InstitutionsToMailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_LettersToPrintCount", IsComposable=true)]
		public System.Nullable<int> fn_Get_LettersToPrintCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_InstDocumentsToPrintCount", IsComposable=true)]
		public System.Nullable<int> fn_Get_InstDocumentsToPrintCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetInstEmailsToSentCount", IsComposable=true)]
		public System.Nullable<int> fn_GetInstEmailsToSentCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_GetSingleEmailsToSendCount", IsComposable=true)]
		public System.Nullable<int> fn_GetSingleEmailsToSendCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduspecService_SingleEmailsToMail")]
		public ISingleResult<Get_EduspecService_SingleEmailsToMailResult> Get_EduspecService_SingleEmailsToMail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduspecService_SingleEmailsToMailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduspecService_SingleEmailSent")]
		public int Set_EduspecService_SingleEmailSent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SingleEmailQueueID", DbType="Int")] System.Nullable<int> singleEmailQueueID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="KeyValueType", DbType="Int")] System.Nullable<int> keyValueType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSent", DbType="Bit")] System.Nullable<bool> isSent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Error", DbType="VarChar(255)")] string error)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), singleEmailQueueID, keyValueType, isSent, error);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_EmailLettersToCreateCount", IsComposable=true)]
		public System.Nullable<int> fn_Get_EmailLettersToCreateCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduSpecService_EmailSent")]
		public ISingleResult<Set_EduSpecService_EmailSentResult> Set_EduSpecService_EmailSent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CorrespondenceID", DbType="Int")] System.Nullable<int> correspondenceID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingKey", DbType="Int")] System.Nullable<int> trackingKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsSent", DbType="Bit")] System.Nullable<bool> isSent, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Error", DbType="VarChar(255)")] string error, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="InstID", DbType="Int")] System.Nullable<int> instID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FamilyID", DbType="Int")] System.Nullable<int> familyID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AgeStatusID", DbType="Int")] System.Nullable<int> ageStatusID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserID", DbType="Int")] System.Nullable<int> userID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailBody", DbType="VarChar(918)")] string emailBody, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Recipient", DbType="VarChar(100)")] string recipient, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cc", DbType="VarChar(200)")] string cc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileName", DbType="VarChar(250)")] string fileName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), correspondenceID, trackingKey, isSent, error, instID, familyID, ageStatusID, userID, emailBody, recipient, cc, fileName);
			return ((ISingleResult<Set_EduSpecService_EmailSentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_SysParams", IsComposable=true)]
		public IQueryable<fn_Get_SysParamsResult> fn_Get_SysParams()
		{
			return this.CreateMethodCallQuery<fn_Get_SysParamsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_Eduspecservice_BulkEmailLettersPrepareCount", IsComposable=true)]
		public System.Nullable<int> fn_Get_Eduspecservice_BulkEmailLettersPrepareCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduSpecService_FamiliesToMail")]
		public ISingleResult<Get_EduSpecService_FamiliesToMailResult> Get_EduSpecService_FamiliesToMail()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduSpecService_FamiliesToMailResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.fn_Get_Eduspecservice_UpdatedEmailPrepareCount", IsComposable=true)]
		public System.Nullable<int> fn_Get_Eduspecservice_UpdatedEmailPrepareCount()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduspecService_UpdatedEmailGenerated")]
		public int Set_EduspecService_UpdatedEmailGenerated([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailCorrespondenceID", DbType="Int")] System.Nullable<int> emailCorrespondenceID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), emailCorrespondenceID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduspecService_UpdatedEmailLetterAttachment_List")]
		public ISingleResult<Get_EduspecService_UpdatedEmailLetterAttachment_ListResult> Get_EduspecService_UpdatedEmailLetterAttachment_List()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduspecService_UpdatedEmailLetterAttachment_ListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduspecService_BulkEmailLetterAttachment_List")]
		public ISingleResult<Get_EduspecService_BulkEmailLetterAttachment_ListResult> Get_EduspecService_BulkEmailLetterAttachment_List()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduspecService_BulkEmailLetterAttachment_ListResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Get_EduSpecService_EmailsToPrepare")]
		public ISingleResult<Get_EduSpecService_EmailsToPrepareResult> Get_EduSpecService_EmailsToPrepare()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Get_EduSpecService_EmailsToPrepareResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Set_EduSpecService_PrepareEmailQueue")]
		public int Set_EduSpecService_PrepareEmailQueue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingKey", DbType="Int")] System.Nullable<int> trackingKey, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsAge", DbType="Bit")] System.Nullable<bool> isAge, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AttachLetter", DbType="Bit")] System.Nullable<bool> attachLetter, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AttachFile", DbType="Bit")] System.Nullable<bool> attachFile)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), trackingKey, isAge, attachLetter, attachFile);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.RPT_Invoice")]
		public ISingleResult<RPT_InvoiceResult> RPT_Invoice([global::System.Data.Linq.Mapping.ParameterAttribute(Name="InvoiceID", DbType="Int")] System.Nullable<int> invoiceID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), invoiceID);
			return ((ISingleResult<RPT_InvoiceResult>)(result.ReturnValue));
		}
	}
	
	public partial class fn_Get_BulkLetterInstitutionListResult
	{
		
		private System.Nullable<int> _InstID;
		
		private System.Nullable<bool> _IsPrintLetterhead;
		
		public fn_Get_BulkLetterInstitutionListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrintLetterhead", DbType="Bit")]
		public System.Nullable<bool> IsPrintLetterhead
		{
			get
			{
				return this._IsPrintLetterhead;
			}
			set
			{
				if ((this._IsPrintLetterhead != value))
				{
					this._IsPrintLetterhead = value;
				}
			}
		}
	}
	
	public partial class RPT_GenericLetterResult
	{
		
		private string _Body;
		
		public RPT_GenericLetterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="VarChar(MAX)")]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this._Body = value;
				}
			}
		}
	}
	
	public partial class RPT_LetterheadResult
	{
		
		private string _InstitutionName;
		
		private string _StreetAddress;
		
		private string _PostalAddress;
		
		private string _Contact;
		
		private string _LogoUrl;
		
		private System.Data.Linq.Binary _Logo;
		
		public RPT_LetterheadResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstitutionName", DbType="VarChar(1000)")]
		public string InstitutionName
		{
			get
			{
				return this._InstitutionName;
			}
			set
			{
				if ((this._InstitutionName != value))
				{
					this._InstitutionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StreetAddress", DbType="VarChar(8000)")]
		public string StreetAddress
		{
			get
			{
				return this._StreetAddress;
			}
			set
			{
				if ((this._StreetAddress != value))
				{
					this._StreetAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostalAddress", DbType="VarChar(8000)")]
		public string PostalAddress
		{
			get
			{
				return this._PostalAddress;
			}
			set
			{
				if ((this._PostalAddress != value))
				{
					this._PostalAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contact", DbType="VarChar(181)")]
		public string Contact
		{
			get
			{
				return this._Contact;
			}
			set
			{
				if ((this._Contact != value))
				{
					this._Contact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogoUrl", DbType="VarChar(100)")]
		public string LogoUrl
		{
			get
			{
				return this._LogoUrl;
			}
			set
			{
				if ((this._LogoUrl != value))
				{
					this._LogoUrl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logo", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Logo
		{
			get
			{
				return this._Logo;
			}
			set
			{
				if ((this._Logo != value))
				{
					this._Logo = value;
				}
			}
		}
	}
	
	public partial class Set_EduSpecService_SMSSentResult
	{
		
		private string _FileNAme;
		
		public Set_EduSpecService_SMSSentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileNAme", DbType="VarChar(250)")]
		public string FileNAme
		{
			get
			{
				return this._FileNAme;
			}
			set
			{
				if ((this._FileNAme != value))
				{
					this._FileNAme = value;
				}
			}
		}
	}
	
	public partial class RPT_Bulk_LettersResult
	{
		
		private string _Body;
		
		public RPT_Bulk_LettersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="VarChar(MAX)")]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this._Body = value;
				}
			}
		}
	}
	
	public partial class RPT_Age_LettersResult
	{
		
		private string _Body;
		
		public RPT_Age_LettersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Body", DbType="VarChar(MAX)")]
		public string Body
		{
			get
			{
				return this._Body;
			}
			set
			{
				if ((this._Body != value))
				{
					this._Body = value;
				}
			}
		}
	}
	
	public partial class Set_DebtManagement_ActionHistoryResult
	{
		
		private string _FileName;
		
		public Set_DebtManagement_ActionHistoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(250)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
	}
	
	public partial class Get_Account_NewInstitutions_ViewResult
	{
		
		private int _InstID;
		
		private int _MasterInstID;
		
		private string _Name;
		
		private string _EMISNo;
		
		private byte _QuintileID;
		
		private byte _PhaseID;
		
		private string _PhysAddress1;
		
		private string _PhysAddress2;
		
		private string _PhysAddress3;
		
		private System.Nullable<byte> _PhysProvinceID;
		
		private string _PhysCode;
		
		private string _PosAddress1;
		
		private string _PosAddress2;
		
		private string _PosAddress3;
		
		private System.Nullable<byte> _PosProvinceID;
		
		private string _PosCode;
		
		private string _Telephone;
		
		private string _Cell;
		
		private string _Fax;
		
		private string _InstEmail;
		
		private System.Nullable<int> _PrincipalID;
		
		private System.Nullable<int> _FinancialSecretoryID;
		
		private System.Nullable<int> _GoverningBodyID;
		
		private System.Nullable<int> _GoverningFinanceID;
		
		private bool _IsActive;
		
		private string _FullName;
		
		private string _Surname;
		
		private string _Email;
		
		private bool _IsRequestEvaluation;
		
		private string _Password;
		
		private int _CorrespondenceLanguageID;
		
		private int _GradeFromID;
		
		private int _GradeToID;
		
		private System.Nullable<int> _IntegrationTypeID;
		
		public Get_Account_NewInstitutions_ViewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int NOT NULL")]
		public int InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterInstID", DbType="Int NOT NULL")]
		public int MasterInstID
		{
			get
			{
				return this._MasterInstID;
			}
			set
			{
				if ((this._MasterInstID != value))
				{
					this._MasterInstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMISNo", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string EMISNo
		{
			get
			{
				return this._EMISNo;
			}
			set
			{
				if ((this._EMISNo != value))
				{
					this._EMISNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuintileID", DbType="TinyInt NOT NULL")]
		public byte QuintileID
		{
			get
			{
				return this._QuintileID;
			}
			set
			{
				if ((this._QuintileID != value))
				{
					this._QuintileID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhaseID", DbType="TinyInt NOT NULL")]
		public byte PhaseID
		{
			get
			{
				return this._PhaseID;
			}
			set
			{
				if ((this._PhaseID != value))
				{
					this._PhaseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysAddress1", DbType="VarChar(50)")]
		public string PhysAddress1
		{
			get
			{
				return this._PhysAddress1;
			}
			set
			{
				if ((this._PhysAddress1 != value))
				{
					this._PhysAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysAddress2", DbType="VarChar(50)")]
		public string PhysAddress2
		{
			get
			{
				return this._PhysAddress2;
			}
			set
			{
				if ((this._PhysAddress2 != value))
				{
					this._PhysAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysAddress3", DbType="VarChar(50)")]
		public string PhysAddress3
		{
			get
			{
				return this._PhysAddress3;
			}
			set
			{
				if ((this._PhysAddress3 != value))
				{
					this._PhysAddress3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysProvinceID", DbType="TinyInt")]
		public System.Nullable<byte> PhysProvinceID
		{
			get
			{
				return this._PhysProvinceID;
			}
			set
			{
				if ((this._PhysProvinceID != value))
				{
					this._PhysProvinceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysCode", DbType="VarChar(7)")]
		public string PhysCode
		{
			get
			{
				return this._PhysCode;
			}
			set
			{
				if ((this._PhysCode != value))
				{
					this._PhysCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosAddress1", DbType="VarChar(50)")]
		public string PosAddress1
		{
			get
			{
				return this._PosAddress1;
			}
			set
			{
				if ((this._PosAddress1 != value))
				{
					this._PosAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosAddress2", DbType="VarChar(50)")]
		public string PosAddress2
		{
			get
			{
				return this._PosAddress2;
			}
			set
			{
				if ((this._PosAddress2 != value))
				{
					this._PosAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosAddress3", DbType="VarChar(50)")]
		public string PosAddress3
		{
			get
			{
				return this._PosAddress3;
			}
			set
			{
				if ((this._PosAddress3 != value))
				{
					this._PosAddress3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosProvinceID", DbType="TinyInt")]
		public System.Nullable<byte> PosProvinceID
		{
			get
			{
				return this._PosProvinceID;
			}
			set
			{
				if ((this._PosProvinceID != value))
				{
					this._PosProvinceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PosCode", DbType="VarChar(7)")]
		public string PosCode
		{
			get
			{
				return this._PosCode;
			}
			set
			{
				if ((this._PosCode != value))
				{
					this._PosCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="VarChar(30)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this._Telephone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cell", DbType="VarChar(30)")]
		public string Cell
		{
			get
			{
				return this._Cell;
			}
			set
			{
				if ((this._Cell != value))
				{
					this._Cell = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(30)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this._Fax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstEmail", DbType="VarChar(100)")]
		public string InstEmail
		{
			get
			{
				return this._InstEmail;
			}
			set
			{
				if ((this._InstEmail != value))
				{
					this._InstEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrincipalID", DbType="Int")]
		public System.Nullable<int> PrincipalID
		{
			get
			{
				return this._PrincipalID;
			}
			set
			{
				if ((this._PrincipalID != value))
				{
					this._PrincipalID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinancialSecretoryID", DbType="Int")]
		public System.Nullable<int> FinancialSecretoryID
		{
			get
			{
				return this._FinancialSecretoryID;
			}
			set
			{
				if ((this._FinancialSecretoryID != value))
				{
					this._FinancialSecretoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoverningBodyID", DbType="Int")]
		public System.Nullable<int> GoverningBodyID
		{
			get
			{
				return this._GoverningBodyID;
			}
			set
			{
				if ((this._GoverningBodyID != value))
				{
					this._GoverningBodyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GoverningFinanceID", DbType="Int")]
		public System.Nullable<int> GoverningFinanceID
		{
			get
			{
				return this._GoverningFinanceID;
			}
			set
			{
				if ((this._GoverningFinanceID != value))
				{
					this._GoverningFinanceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit NOT NULL")]
		public bool IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="VarChar(100)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this._FullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(100)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(150)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRequestEvaluation", DbType="Bit NOT NULL")]
		public bool IsRequestEvaluation
		{
			get
			{
				return this._IsRequestEvaluation;
			}
			set
			{
				if ((this._IsRequestEvaluation != value))
				{
					this._IsRequestEvaluation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(100)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrespondenceLanguageID", DbType="Int NOT NULL")]
		public int CorrespondenceLanguageID
		{
			get
			{
				return this._CorrespondenceLanguageID;
			}
			set
			{
				if ((this._CorrespondenceLanguageID != value))
				{
					this._CorrespondenceLanguageID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeFromID", DbType="Int NOT NULL")]
		public int GradeFromID
		{
			get
			{
				return this._GradeFromID;
			}
			set
			{
				if ((this._GradeFromID != value))
				{
					this._GradeFromID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GradeToID", DbType="Int NOT NULL")]
		public int GradeToID
		{
			get
			{
				return this._GradeToID;
			}
			set
			{
				if ((this._GradeToID != value))
				{
					this._GradeToID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IntegrationTypeID", DbType="Int")]
		public System.Nullable<int> IntegrationTypeID
		{
			get
			{
				return this._IntegrationTypeID;
			}
			set
			{
				if ((this._IntegrationTypeID != value))
				{
					this._IntegrationTypeID = value;
				}
			}
		}
	}
	
	public partial class Get_EduspecService_BulkLetterQueue_ListResult
	{
		
		private int _LetterCorrespondenceID;
		
		private System.Nullable<int> _LetterTrackingKey;
		
		private int _FamilyID;
		
		private System.Nullable<int> _InstID;
		
		private System.Nullable<int> _StatusID;
		
		private System.Nullable<int> _LetterID;
		
		private System.Nullable<int> _UserID;
		
		private System.Nullable<bool> _IsPrintLetterhead;
		
		public Get_EduspecService_BulkLetterQueue_ListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterCorrespondenceID", DbType="Int NOT NULL")]
		public int LetterCorrespondenceID
		{
			get
			{
				return this._LetterCorrespondenceID;
			}
			set
			{
				if ((this._LetterCorrespondenceID != value))
				{
					this._LetterCorrespondenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterTrackingKey", DbType="Int")]
		public System.Nullable<int> LetterTrackingKey
		{
			get
			{
				return this._LetterTrackingKey;
			}
			set
			{
				if ((this._LetterTrackingKey != value))
				{
					this._LetterTrackingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyID", DbType="Int NOT NULL")]
		public int FamilyID
		{
			get
			{
				return this._FamilyID;
			}
			set
			{
				if ((this._FamilyID != value))
				{
					this._FamilyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int")]
		public System.Nullable<int> StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this._StatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterID", DbType="Int")]
		public System.Nullable<int> LetterID
		{
			get
			{
				return this._LetterID;
			}
			set
			{
				if ((this._LetterID != value))
				{
					this._LetterID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrintLetterhead", DbType="Bit")]
		public System.Nullable<bool> IsPrintLetterhead
		{
			get
			{
				return this._IsPrintLetterhead;
			}
			set
			{
				if ((this._IsPrintLetterhead != value))
				{
					this._IsPrintLetterhead = value;
				}
			}
		}
	}
	
	public partial class Get_EduspecService_BulkLetterTracking_ListResult
	{
		
		private int _LetterTrackingKey;
		
		private System.Nullable<bool> _IsPrintLetterhead;
		
		private string _FileName;
		
		private System.Nullable<int> _InstID;
		
		public Get_EduspecService_BulkLetterTracking_ListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LetterTrackingKey", DbType="Int NOT NULL")]
		public int LetterTrackingKey
		{
			get
			{
				return this._LetterTrackingKey;
			}
			set
			{
				if ((this._LetterTrackingKey != value))
				{
					this._LetterTrackingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrintLetterhead", DbType="Bit")]
		public System.Nullable<bool> IsPrintLetterhead
		{
			get
			{
				return this._IsPrintLetterhead;
			}
			set
			{
				if ((this._IsPrintLetterhead != value))
				{
					this._IsPrintLetterhead = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(250)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
	}
	
	public partial class Get_CorrespondenceMethod_PickListResult
	{
		
		private int _ID;
		
		private string _Description;
		
		public Get_CorrespondenceMethod_PickListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(40)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class Get_EduSpecService_SMSsToPrepareResult
	{
		
		private int _SMSTrackingKey;
		
		private System.Nullable<int> _InstID;
		
		private string _Name;
		
		private System.Nullable<int> _InstSMSID;
		
		private string _Description;
		
		public Get_EduSpecService_SMSsToPrepareResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSTrackingKey", DbType="Int NOT NULL")]
		public int SMSTrackingKey
		{
			get
			{
				return this._SMSTrackingKey;
			}
			set
			{
				if ((this._SMSTrackingKey != value))
				{
					this._SMSTrackingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstSMSID", DbType="Int")]
		public System.Nullable<int> InstSMSID
		{
			get
			{
				return this._InstSMSID;
			}
			set
			{
				if ((this._InstSMSID != value))
				{
					this._InstSMSID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
	}
	
	public partial class Get_EduSpecService_SMSsToSentResult
	{
		
		private int _SMSCorrespondenceID;
		
		private System.Nullable<int> _SMSTrackingKey;
		
		private string _CellNumber;
		
		private string _SMSMessage;
		
		public Get_EduSpecService_SMSsToSentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSCorrespondenceID", DbType="Int NOT NULL")]
		public int SMSCorrespondenceID
		{
			get
			{
				return this._SMSCorrespondenceID;
			}
			set
			{
				if ((this._SMSCorrespondenceID != value))
				{
					this._SMSCorrespondenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSTrackingKey", DbType="Int")]
		public System.Nullable<int> SMSTrackingKey
		{
			get
			{
				return this._SMSTrackingKey;
			}
			set
			{
				if ((this._SMSTrackingKey != value))
				{
					this._SMSTrackingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellNumber", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string CellNumber
		{
			get
			{
				return this._CellNumber;
			}
			set
			{
				if ((this._CellNumber != value))
				{
					this._CellNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMSMessage", DbType="VarChar(918)")]
		public string SMSMessage
		{
			get
			{
				return this._SMSMessage;
			}
			set
			{
				if ((this._SMSMessage != value))
				{
					this._SMSMessage = value;
				}
			}
		}
	}
	
	public partial class Get_EduspecService_DocumentsToGenerateResult
	{
		
		private int _CorrespondenceID;
		
		private int _DocumentID;
		
		private System.Nullable<int> _DocumentTypeID;
		
		private string _DocumentDesc;
		
		private System.Nullable<int> _InstID;
		
		private string _EmailSubject;
		
		public Get_EduspecService_DocumentsToGenerateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrespondenceID", DbType="Int NOT NULL")]
		public int CorrespondenceID
		{
			get
			{
				return this._CorrespondenceID;
			}
			set
			{
				if ((this._CorrespondenceID != value))
				{
					this._CorrespondenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentID", DbType="Int NOT NULL")]
		public int DocumentID
		{
			get
			{
				return this._DocumentID;
			}
			set
			{
				if ((this._DocumentID != value))
				{
					this._DocumentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentTypeID", DbType="Int")]
		public System.Nullable<int> DocumentTypeID
		{
			get
			{
				return this._DocumentTypeID;
			}
			set
			{
				if ((this._DocumentTypeID != value))
				{
					this._DocumentTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentDesc", DbType="VarChar(100)")]
		public string DocumentDesc
		{
			get
			{
				return this._DocumentDesc;
			}
			set
			{
				if ((this._DocumentDesc != value))
				{
					this._DocumentDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="VarChar(200)")]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this._EmailSubject = value;
				}
			}
		}
	}
	
	public partial class RPT_StatementResult
	{
		
		private System.Nullable<System.DateTime> _DateDone;
		
		private string _Description;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<decimal> _RunningTotal;
		
		public RPT_StatementResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateDone", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateDone
		{
			get
			{
				return this._DateDone;
			}
			set
			{
				if ((this._DateDone != value))
				{
					this._DateDone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(112)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this._Amount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunningTotal", DbType="Money")]
		public System.Nullable<decimal> RunningTotal
		{
			get
			{
				return this._RunningTotal;
			}
			set
			{
				if ((this._RunningTotal != value))
				{
					this._RunningTotal = value;
				}
			}
		}
	}
	
	public partial class RPT_StatementFooterResult
	{
		
		private int _InstID;
		
		private System.Nullable<decimal> _CurrentAmount;
		
		private System.Nullable<decimal> @__30DaysAmount;
		
		private System.Nullable<decimal> @__60DaysAmount;
		
		private System.Nullable<decimal> @__90DaysAmount;
		
		private System.Nullable<decimal> @__120DaysPlus;
		
		public RPT_StatementFooterResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int NOT NULL")]
		public int InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrentAmount", DbType="Money")]
		public System.Nullable<decimal> CurrentAmount
		{
			get
			{
				return this._CurrentAmount;
			}
			set
			{
				if ((this._CurrentAmount != value))
				{
					this._CurrentAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[30DaysAmount]", Storage="__30DaysAmount", DbType="Money")]
		public System.Nullable<decimal> _30DaysAmount
		{
			get
			{
				return this.@__30DaysAmount;
			}
			set
			{
				if ((this.@__30DaysAmount != value))
				{
					this.@__30DaysAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[60DaysAmount]", Storage="__60DaysAmount", DbType="Money")]
		public System.Nullable<decimal> _60DaysAmount
		{
			get
			{
				return this.@__60DaysAmount;
			}
			set
			{
				if ((this.@__60DaysAmount != value))
				{
					this.@__60DaysAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[90DaysAmount]", Storage="__90DaysAmount", DbType="Money")]
		public System.Nullable<decimal> _90DaysAmount
		{
			get
			{
				return this.@__90DaysAmount;
			}
			set
			{
				if ((this.@__90DaysAmount != value))
				{
					this.@__90DaysAmount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[120DaysPlus]", Storage="__120DaysPlus", DbType="Money")]
		public System.Nullable<decimal> _120DaysPlus
		{
			get
			{
				return this.@__120DaysPlus;
			}
			set
			{
				if ((this.@__120DaysPlus != value))
				{
					this.@__120DaysPlus = value;
				}
			}
		}
	}
	
	public partial class RPT_StatementHeaderResult
	{
		
		private string _BillTo;
		
		private string _VATNumber;
		
		public RPT_StatementHeaderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillTo", DbType="VarChar(5000)")]
		public string BillTo
		{
			get
			{
				return this._BillTo;
			}
			set
			{
				if ((this._BillTo != value))
				{
					this._BillTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATNumber", DbType="VarChar(20)")]
		public string VATNumber
		{
			get
			{
				return this._VATNumber;
			}
			set
			{
				if ((this._VATNumber != value))
				{
					this._VATNumber = value;
				}
			}
		}
	}
	
	public partial class RPT_InvoiceHeaderResult
	{
		
		private System.Nullable<System.DateTime> _InvoiceDate;
		
		private string _BillTo;
		
		private string _InvoiceNumber;
		
		private string _VATNumber;
		
		public RPT_InvoiceHeaderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this._InvoiceDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillTo", DbType="VarChar(5000)")]
		public string BillTo
		{
			get
			{
				return this._BillTo;
			}
			set
			{
				if ((this._BillTo != value))
				{
					this._BillTo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNumber", DbType="VarChar(30)")]
		public string InvoiceNumber
		{
			get
			{
				return this._InvoiceNumber;
			}
			set
			{
				if ((this._InvoiceNumber != value))
				{
					this._InvoiceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATNumber", DbType="VarChar(20)")]
		public string VATNumber
		{
			get
			{
				return this._VATNumber;
			}
			set
			{
				if ((this._VATNumber != value))
				{
					this._VATNumber = value;
				}
			}
		}
	}
	
	public partial class Get_EduspecService_InstitutionsToMailResult
	{
		
		private int _CorrespondenceID;
		
		private int _DocumentID;
		
		private System.Nullable<int> _DocumentTypeID;
		
		private System.Nullable<int> _InstID;
		
		private string _InstName;
		
		private string _EmailSubject;
		
		private string _EmailBody;
		
		private string _FileName;
		
		private string _EmailRecipient;
		
		public Get_EduspecService_InstitutionsToMailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CorrespondenceID", DbType="Int NOT NULL")]
		public int CorrespondenceID
		{
			get
			{
				return this._CorrespondenceID;
			}
			set
			{
				if ((this._CorrespondenceID != value))
				{
					this._CorrespondenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentID", DbType="Int NOT NULL")]
		public int DocumentID
		{
			get
			{
				return this._DocumentID;
			}
			set
			{
				if ((this._DocumentID != value))
				{
					this._DocumentID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentTypeID", DbType="Int")]
		public System.Nullable<int> DocumentTypeID
		{
			get
			{
				return this._DocumentTypeID;
			}
			set
			{
				if ((this._DocumentTypeID != value))
				{
					this._DocumentTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string InstName
		{
			get
			{
				return this._InstName;
			}
			set
			{
				if ((this._InstName != value))
				{
					this._InstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="VarChar(200)")]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this._EmailSubject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBody", DbType="VarChar(292)")]
		public string EmailBody
		{
			get
			{
				return this._EmailBody;
			}
			set
			{
				if ((this._EmailBody != value))
				{
					this._EmailBody = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(250)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailRecipient", DbType="VarChar(150)")]
		public string EmailRecipient
		{
			get
			{
				return this._EmailRecipient;
			}
			set
			{
				if ((this._EmailRecipient != value))
				{
					this._EmailRecipient = value;
				}
			}
		}
	}
	
	public partial class Get_EduspecService_SingleEmailsToMailResult
	{
		
		private int _SingleEmailQueueID;
		
		private System.Nullable<int> _KeyValueType;
		
		private string _InstName;
		
		private string _Recipient;
		
		private string _Cc;
		
		private string _Subject;
		
		private string _EmailMessage;
		
		private string _FileName;
		
		public Get_EduspecService_SingleEmailsToMailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SingleEmailQueueID", DbType="Int NOT NULL")]
		public int SingleEmailQueueID
		{
			get
			{
				return this._SingleEmailQueueID;
			}
			set
			{
				if ((this._SingleEmailQueueID != value))
				{
					this._SingleEmailQueueID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyValueType", DbType="Int")]
		public System.Nullable<int> KeyValueType
		{
			get
			{
				return this._KeyValueType;
			}
			set
			{
				if ((this._KeyValueType != value))
				{
					this._KeyValueType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstName", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string InstName
		{
			get
			{
				return this._InstName;
			}
			set
			{
				if ((this._InstName != value))
				{
					this._InstName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recipient", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Recipient
		{
			get
			{
				return this._Recipient;
			}
			set
			{
				if ((this._Recipient != value))
				{
					this._Recipient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cc", DbType="VarChar(100)")]
		public string Cc
		{
			get
			{
				return this._Cc;
			}
			set
			{
				if ((this._Cc != value))
				{
					this._Cc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="VarChar(100)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this._Subject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailMessage", DbType="VarChar(MAX)")]
		public string EmailMessage
		{
			get
			{
				return this._EmailMessage;
			}
			set
			{
				if ((this._EmailMessage != value))
				{
					this._EmailMessage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(250)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
	}
	
	public partial class Set_EduSpecService_EmailSentResult
	{
		
		private string _FileName;
		
		public Set_EduSpecService_EmailSentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(250)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
	}
	
	public partial class fn_Get_SysParamsResult
	{
		
		private System.Nullable<decimal> _VAT;
		
		private string _VATNumber;
		
		private string _InstitutionInvoiceFilePath;
		
		private string _ApplicationsFilePath;
		
		private string _PrintoutsFilePath;
		
		private string _AgeAnalysisFilePath;
		
		private string _InstitutionDataUploadFilePath;
		
		private string _QuotationFilePath;
		
		private string _EmailUploadFilePath;
		
		private string _SupportUploadFilePath;
		
		private string _InstitutionDocumentsFilePath;
		
		private string _AccessDatabaseProvider;
		
		private string _EmailAttachements;
		
		private string _SASAMS_Password;
		
		private string _SQL_Server;
		
		private string _SQL_Database;
		
		private string _SQL_User;
		
		private string _SQL_Password;
		
		public fn_Get_SysParamsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="Decimal(6,3)")]
		public System.Nullable<decimal> VAT
		{
			get
			{
				return this._VAT;
			}
			set
			{
				if ((this._VAT != value))
				{
					this._VAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VATNumber", DbType="VarChar(20)")]
		public string VATNumber
		{
			get
			{
				return this._VATNumber;
			}
			set
			{
				if ((this._VATNumber != value))
				{
					this._VATNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstitutionInvoiceFilePath", DbType="VarChar(150)")]
		public string InstitutionInvoiceFilePath
		{
			get
			{
				return this._InstitutionInvoiceFilePath;
			}
			set
			{
				if ((this._InstitutionInvoiceFilePath != value))
				{
					this._InstitutionInvoiceFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationsFilePath", DbType="VarChar(150)")]
		public string ApplicationsFilePath
		{
			get
			{
				return this._ApplicationsFilePath;
			}
			set
			{
				if ((this._ApplicationsFilePath != value))
				{
					this._ApplicationsFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintoutsFilePath", DbType="VarChar(150)")]
		public string PrintoutsFilePath
		{
			get
			{
				return this._PrintoutsFilePath;
			}
			set
			{
				if ((this._PrintoutsFilePath != value))
				{
					this._PrintoutsFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgeAnalysisFilePath", DbType="VarChar(150)")]
		public string AgeAnalysisFilePath
		{
			get
			{
				return this._AgeAnalysisFilePath;
			}
			set
			{
				if ((this._AgeAnalysisFilePath != value))
				{
					this._AgeAnalysisFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstitutionDataUploadFilePath", DbType="VarChar(150)")]
		public string InstitutionDataUploadFilePath
		{
			get
			{
				return this._InstitutionDataUploadFilePath;
			}
			set
			{
				if ((this._InstitutionDataUploadFilePath != value))
				{
					this._InstitutionDataUploadFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuotationFilePath", DbType="VarChar(150)")]
		public string QuotationFilePath
		{
			get
			{
				return this._QuotationFilePath;
			}
			set
			{
				if ((this._QuotationFilePath != value))
				{
					this._QuotationFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailUploadFilePath", DbType="VarChar(150)")]
		public string EmailUploadFilePath
		{
			get
			{
				return this._EmailUploadFilePath;
			}
			set
			{
				if ((this._EmailUploadFilePath != value))
				{
					this._EmailUploadFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupportUploadFilePath", DbType="VarChar(150)")]
		public string SupportUploadFilePath
		{
			get
			{
				return this._SupportUploadFilePath;
			}
			set
			{
				if ((this._SupportUploadFilePath != value))
				{
					this._SupportUploadFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstitutionDocumentsFilePath", DbType="VarChar(150)")]
		public string InstitutionDocumentsFilePath
		{
			get
			{
				return this._InstitutionDocumentsFilePath;
			}
			set
			{
				if ((this._InstitutionDocumentsFilePath != value))
				{
					this._InstitutionDocumentsFilePath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccessDatabaseProvider", DbType="VarChar(150)")]
		public string AccessDatabaseProvider
		{
			get
			{
				return this._AccessDatabaseProvider;
			}
			set
			{
				if ((this._AccessDatabaseProvider != value))
				{
					this._AccessDatabaseProvider = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailAttachements", DbType="VarChar(150)")]
		public string EmailAttachements
		{
			get
			{
				return this._EmailAttachements;
			}
			set
			{
				if ((this._EmailAttachements != value))
				{
					this._EmailAttachements = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SASAMS_Password", DbType="VarChar(10)")]
		public string SASAMS_Password
		{
			get
			{
				return this._SASAMS_Password;
			}
			set
			{
				if ((this._SASAMS_Password != value))
				{
					this._SASAMS_Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL_Server", DbType="VarChar(150)")]
		public string SQL_Server
		{
			get
			{
				return this._SQL_Server;
			}
			set
			{
				if ((this._SQL_Server != value))
				{
					this._SQL_Server = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL_Database", DbType="VarChar(50)")]
		public string SQL_Database
		{
			get
			{
				return this._SQL_Database;
			}
			set
			{
				if ((this._SQL_Database != value))
				{
					this._SQL_Database = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL_User", DbType="VarChar(50)")]
		public string SQL_User
		{
			get
			{
				return this._SQL_User;
			}
			set
			{
				if ((this._SQL_User != value))
				{
					this._SQL_User = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQL_Password", DbType="VarChar(50)")]
		public string SQL_Password
		{
			get
			{
				return this._SQL_Password;
			}
			set
			{
				if ((this._SQL_Password != value))
				{
					this._SQL_Password = value;
				}
			}
		}
	}
	
	public partial class Get_EduSpecService_FamiliesToMailResult
	{
		
		private int _EmailCorrespondenceID;
		
		private string _Name;
		
		private string _Recipient;
		
		private string _Cc;
		
		private string _EmailSubject;
		
		private string _EmailBody;
		
		private string _FileName;
		
		private int _EmailTrackingKey;
		
		private System.Nullable<int> _InstID;
		
		private int _FamilyID;
		
		private System.Nullable<int> _StatusID;
		
		private System.Nullable<int> _UserID;
		
		private bool _IsAge;
		
		public Get_EduSpecService_FamiliesToMailResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailCorrespondenceID", DbType="Int NOT NULL")]
		public int EmailCorrespondenceID
		{
			get
			{
				return this._EmailCorrespondenceID;
			}
			set
			{
				if ((this._EmailCorrespondenceID != value))
				{
					this._EmailCorrespondenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recipient", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Recipient
		{
			get
			{
				return this._Recipient;
			}
			set
			{
				if ((this._Recipient != value))
				{
					this._Recipient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cc", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Cc
		{
			get
			{
				return this._Cc;
			}
			set
			{
				if ((this._Cc != value))
				{
					this._Cc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSubject", DbType="VarChar(200)")]
		public string EmailSubject
		{
			get
			{
				return this._EmailSubject;
			}
			set
			{
				if ((this._EmailSubject != value))
				{
					this._EmailSubject = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailBody", DbType="VarChar(MAX)")]
		public string EmailBody
		{
			get
			{
				return this._EmailBody;
			}
			set
			{
				if ((this._EmailBody != value))
				{
					this._EmailBody = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(250)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTrackingKey", DbType="Int NOT NULL")]
		public int EmailTrackingKey
		{
			get
			{
				return this._EmailTrackingKey;
			}
			set
			{
				if ((this._EmailTrackingKey != value))
				{
					this._EmailTrackingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyID", DbType="Int NOT NULL")]
		public int FamilyID
		{
			get
			{
				return this._FamilyID;
			}
			set
			{
				if ((this._FamilyID != value))
				{
					this._FamilyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int")]
		public System.Nullable<int> StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this._StatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAge", DbType="Bit NOT NULL")]
		public bool IsAge
		{
			get
			{
				return this._IsAge;
			}
			set
			{
				if ((this._IsAge != value))
				{
					this._IsAge = value;
				}
			}
		}
	}
	
	public partial class Get_EduspecService_UpdatedEmailLetterAttachment_ListResult
	{
		
		private int _EmailCorrespondenceID;
		
		private System.Nullable<int> _InstID;
		
		private System.Nullable<int> _StatusID;
		
		private int _FamilyID;
		
		private System.Nullable<int> _InstLetterID;
		
		private bool _IsPrintLetterHead;
		
		private string _FileName;
		
		private bool _IsAge;
		
		public Get_EduspecService_UpdatedEmailLetterAttachment_ListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailCorrespondenceID", DbType="Int NOT NULL")]
		public int EmailCorrespondenceID
		{
			get
			{
				return this._EmailCorrespondenceID;
			}
			set
			{
				if ((this._EmailCorrespondenceID != value))
				{
					this._EmailCorrespondenceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int")]
		public System.Nullable<int> StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this._StatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyID", DbType="Int NOT NULL")]
		public int FamilyID
		{
			get
			{
				return this._FamilyID;
			}
			set
			{
				if ((this._FamilyID != value))
				{
					this._FamilyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstLetterID", DbType="Int")]
		public System.Nullable<int> InstLetterID
		{
			get
			{
				return this._InstLetterID;
			}
			set
			{
				if ((this._InstLetterID != value))
				{
					this._InstLetterID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrintLetterHead", DbType="Bit NOT NULL")]
		public bool IsPrintLetterHead
		{
			get
			{
				return this._IsPrintLetterHead;
			}
			set
			{
				if ((this._IsPrintLetterHead != value))
				{
					this._IsPrintLetterHead = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(250)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAge", DbType="Bit NOT NULL")]
		public bool IsAge
		{
			get
			{
				return this._IsAge;
			}
			set
			{
				if ((this._IsAge != value))
				{
					this._IsAge = value;
				}
			}
		}
	}
	
	public partial class Get_EduspecService_BulkEmailLetterAttachment_ListResult
	{
		
		private System.Nullable<int> _InstID;
		
		private System.Nullable<int> _StatusID;
		
		private int _FamilyID;
		
		private System.Nullable<int> _InstLetterID;
		
		private bool _IsPrintLetterHead;
		
		private string _FileName;
		
		private bool _IsAge;
		
		private System.Nullable<bool> _AttachFile;
		
		public Get_EduspecService_BulkEmailLetterAttachment_ListResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstID", DbType="Int")]
		public System.Nullable<int> InstID
		{
			get
			{
				return this._InstID;
			}
			set
			{
				if ((this._InstID != value))
				{
					this._InstID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StatusID", DbType="Int")]
		public System.Nullable<int> StatusID
		{
			get
			{
				return this._StatusID;
			}
			set
			{
				if ((this._StatusID != value))
				{
					this._StatusID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyID", DbType="Int NOT NULL")]
		public int FamilyID
		{
			get
			{
				return this._FamilyID;
			}
			set
			{
				if ((this._FamilyID != value))
				{
					this._FamilyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstLetterID", DbType="Int")]
		public System.Nullable<int> InstLetterID
		{
			get
			{
				return this._InstLetterID;
			}
			set
			{
				if ((this._InstLetterID != value))
				{
					this._InstLetterID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPrintLetterHead", DbType="Bit NOT NULL")]
		public bool IsPrintLetterHead
		{
			get
			{
				return this._IsPrintLetterHead;
			}
			set
			{
				if ((this._IsPrintLetterHead != value))
				{
					this._IsPrintLetterHead = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(250)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this._FileName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAge", DbType="Bit NOT NULL")]
		public bool IsAge
		{
			get
			{
				return this._IsAge;
			}
			set
			{
				if ((this._IsAge != value))
				{
					this._IsAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachFile", DbType="Bit")]
		public System.Nullable<bool> AttachFile
		{
			get
			{
				return this._AttachFile;
			}
			set
			{
				if ((this._AttachFile != value))
				{
					this._AttachFile = value;
				}
			}
		}
	}
	
	public partial class Get_EduSpecService_EmailsToPrepareResult
	{
		
		private int _EmailTrackingKey;
		
		private bool _IsAge;
		
		private bool _AttachLetter;
		
		private System.Nullable<bool> _AttachFile;
		
		public Get_EduSpecService_EmailsToPrepareResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailTrackingKey", DbType="Int NOT NULL")]
		public int EmailTrackingKey
		{
			get
			{
				return this._EmailTrackingKey;
			}
			set
			{
				if ((this._EmailTrackingKey != value))
				{
					this._EmailTrackingKey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAge", DbType="Bit NOT NULL")]
		public bool IsAge
		{
			get
			{
				return this._IsAge;
			}
			set
			{
				if ((this._IsAge != value))
				{
					this._IsAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachLetter", DbType="Bit NOT NULL")]
		public bool AttachLetter
		{
			get
			{
				return this._AttachLetter;
			}
			set
			{
				if ((this._AttachLetter != value))
				{
					this._AttachLetter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttachFile", DbType="Bit")]
		public System.Nullable<bool> AttachFile
		{
			get
			{
				return this._AttachFile;
			}
			set
			{
				if ((this._AttachFile != value))
				{
					this._AttachFile = value;
				}
			}
		}
	}
	
	public partial class RPT_InvoiceResult
	{
		
		private int _InvoiceID;
		
		private int _Quantity;
		
		private string _Description;
		
		private System.Nullable<decimal> _LineTotal;
		
		private System.Nullable<decimal> _Subtotal;
		
		private System.Nullable<decimal> _VAT;
		
		private System.Nullable<decimal> _Total;
		
		public RPT_InvoiceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceID", DbType="Int NOT NULL")]
		public int InvoiceID
		{
			get
			{
				return this._InvoiceID;
			}
			set
			{
				if ((this._InvoiceID != value))
				{
					this._InvoiceID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(100)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineTotal", DbType="Money")]
		public System.Nullable<decimal> LineTotal
		{
			get
			{
				return this._LineTotal;
			}
			set
			{
				if ((this._LineTotal != value))
				{
					this._LineTotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", DbType="Money")]
		public System.Nullable<decimal> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this._Subtotal = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> VAT
		{
			get
			{
				return this._VAT;
			}
			set
			{
				if ((this._VAT != value))
				{
					this._VAT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(38,6)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
